(define (problem exp4)
(:domain calculator)
(:objects A B C D ABCD ABC BCD BC AB CD)
(:INIT (AVAILABLE A) 
       (AVAILABLE B) 
       (AVAILABLE C) 
       (AVAILABLE D) 
       (CANDO-ADD A B) 
       (CANDO-ADD A BC) 
       (CANDO-ADD A BCD) 
       (CANDO-MULT AB CD) 
       (CANDO-MULT AB C) 
       (CANDO-MULT B C) 
       (CANDO-MULT B CD) 
       (CANDO-MINUS ABC D) 
       (CANDO-MINUS BC D) 
       (CANDO-MINUS C D) 
       (NOPART-MULT A)
       (NOPART-MULT BC)
       (NOPART-MULT ABC)
       (NOPART-MULT BCD)
       (NOPART-MULT D)
       (NOPART-DIV  A)
       (NOPART-DIV  B)
       (NOPART-DIV  C)
       (NOPART-DIV  D)
       (NOPART-DIV  AB)
       (NOPART-DIV  BC)
       (NOPART-DIV  CD)
       (NOPART-DIV  ABC)
       (NOPART-DIV  BCD)
       (GIVES A   BCD ABCD)
       (GIVES AB  CD  ABCD)
       (GIVES ABC D   ABCD)
       (GIVES AB  C   ABC)
       (GIVES A   BC  ABC)
       (GIVES B   CD  BCD)
       (GIVES BC  D   BCD)
       (GIVES B   C   BC)
       (GIVES C   D   CD)
       (GIVES A   B   AB)
       (GIVES C   D   CD))
(:goal (and (ASSIGN ABCD)))
)