(define (problem simple)
(:domain calculator)
(:objects A B C D E ABCDE BCDE BCD BC CDE CD DE)
(:INIT (AVAILABLE A) 
       (AVAILABLE B) 
       (AVAILABLE C) 
       (AVAILABLE D) 
       (AVAILABLE E)
       (CANDO-ADD A B) 
       (CANDO-ADD A BC) 
       (CANDO-ADD A BCD) 
       (CANDO-ADD A BCDE)
       (CANDO-MULT B C) 
       (CANDO-MULT B CD) 
       (CANDO-MULT B CDE) 
       (CANDO-MINUS C D) 
       (CANDO-MINUS C DE) 
       (CANDO-DIV   D E)
       (NOPART-MULT A)
       (NOPART-DIV  A)
       (CANCOMPUTE ABCDE)
       (CANCOMPUTE BCDE)
       (CANCOMPUTE BCD)
       (CANCOMPUTE BC)
       (CANCOMPUTE CDE)
       (CANCOMPUTE CD)
       (CANCOMPUTE DE))
(:goal (and (DONE-MULT B C) (DONE-ADD A B) (DONE-MINUS C D)
        (DONE-DIV D E) (ASSIGN ABCDE)))
)