(define (problem exp2)
(:domain calculator)
(:objects B C BC)
(:INIT (AVAILABLE B) 
       (AVAILABLE C) 
       (CANDO-MULT B C) 
       (CANDO-MULT C B) 
       (GIVES B C  BC))
(:goal (and (ASSIGN BC)))
)