(define (problem exp3)
(:domain calculator)
(:objects A B C ABC AB BC)
(:INIT (AVAILABLE A) 
       (AVAILABLE B) 
       (AVAILABLE C) 
       (CANDO-ADD A B) 
       (CANDO-ADD A BC) 
       (CANDO-MULT B C) 
       (CANDO-MULT AB C) 
       (NOPART-MULT A)
       (NOPART-MULT BC)
       (NOPART-DIV  A)
       (NOPART-DIV  B)
       (NOPART-DIV  C)
       (NOPART-DIV  AB)
       (NOPART-DIV  BC)
       (GIVES A BC ABC)
       (GIVES AB C ABC)
       (GIVES A B  AB)
       (GIVES B C  BC))
(:goal (and (ASSIGN ABC)))
)