(define (problem exp5)
(:domain calculator)
(:objects A B C D E ABCDE ABCD ABC AB BCDE BCD BC CDE CD DE)
(:INIT (AVAILABLE A) 
       (AVAILABLE B) 
       (AVAILABLE C) 
       (AVAILABLE D) 
       (AVAILABLE E) 
       (CANDO-ADD A B) 
       (CANDO-ADD A BC) 
       (CANDO-ADD A BCD) 
       (CANDO-ADD A BCDE) 
       (CANDO-MULT AB CDE) 
       (CANDO-MULT AB CD) 
       (CANDO-MULT AB C) 
       (CANDO-MULT B C) 
       (CANDO-MULT B CD) 
       (CANDO-MULT B CDE) 
       (CANDO-MINUS ABC DE) 
       (CANDO-MINUS BC DE) 
       (CANDO-MINUS C DE) 
       (CANDO-MINUS C D) 
       (CANDO-DIV   ABCD E) 
       (CANDO-DIV   BCD E) 
       (CANDO-DIV   CD E) 
       (CANDO-DIV   D E) 
       (NOPART-MULT A)
       (NOPART-MULT BC)
       (NOPART-MULT ABC)
       (NOPART-MULT ABCD)
       (NOPART-MULT BCD)
       (NOPART-MULT BCDE)
       (NOPART-MULT DE)
       (NOPART-MULT D)
       (NOPART-MULT E)
       (NOPART-DIV  A)
       (NOPART-DIV  B)
       (NOPART-DIV  C)
       (NOPART-DIV  AB)
       (NOPART-DIV  ABC)
       (NOPART-DIV  BC)
       (NOPART-DIV  BCDE)
       (NOPART-DIV  CDE)
       (NOPART-DIV  DE)
       (NOPART-DIV  ABC)
       (GIVES A    B    AB)
       (GIVES A    BC   ABC)
       (GIVES AB   C    ABC)
       (GIVES ABC  D    ABCD)
       (GIVES A    BCD  ABCD)
       (GIVES A    BCDE ABCDE)
       (GIVES AB   CDE  ABCDE)
       (GIVES ABC  DE   ABCDE)
       (GIVES ABCD E    ABCDE)
       (GIVES B    C    BC)
       (GIVES B    CD   BCD)
       (GIVES BC   D    BCD)
       (GIVES B    CDE  BCDE)
       (GIVES BC   DE   BCDE)
       (GIVES BCD  E    BCDE)
       (GIVES C    D    CD)
       (GIVES C    DE   CDE)
       (GIVES CD   E    CDE)
       (GIVES D    E    DE))
(:goal (and (ASSIGN ABCDE)))
)